environment:
  nuget_apikey:
    secure: NA0EKAM00TprdvoXc3jg2q72aqHEpZHgBZkYbMq6sBKNItP8VZ8zrsdfTHiYeEJF
image: WMF 5
install:
  - ps: .\buildscripts\install.ps1
build_script:
  - ps: .\buildscripts\build.ps1
after_build:
  - ps: .\buildscripts\publish.ps1
